import type { DirectoryBadgeItem } from "./directory-badges";

export const DIRECTORY_BADGE_ITEMS: DirectoryBadgeItem[] = [
  {
    // Link-only example
    id: "directory-link-example",
    name: "Directory Example",
    href: "https://example.com/your-listing",
    mode: "link",
    linkLabel: "Listed on Directory Example",
    active: false,
    note: "Replace with your actual listing URL and set active to true.",
  },
  {
    // Badge + link example
    id: "directory-badge-example",
    name: "Badge Example",
    href: "https://example.com/your-listing",
    mode: "badge+link",
    badgeSrc: "https://img.shields.io/badge/Listed-Example-blue",
    badgeAlt: "Listed on Example",
    badgeWidth: 200,
    badgeHeight: 54,
    active: false,
    note: "Use the badge image provided by each directory.",
  },
  {
    id: "wired-business",
    name: "Wired Business",
    href: "https://wired.business",
    mode: "badge",
    badgeSrc: "https://wired.business/badge0-light.svg",
    badgeAlt: "Featured on Wired Business",
    badgeWidth: 200,
    badgeHeight: 54,
    active: true,
    target: "_blank",
    note: "Added from provided embed snippet.",
  },
    {
    id: "showmebest",
    name: "showmebest",
    href: "https://showmebest.ai",
    mode: "badge",
    badgeSrc: "https://showmebest.ai/badge/feature-badge-white.webp",
    badgeAlt: "Featured on ShowMeBestAI",
    badgeWidth: 220,
    badgeHeight: 60,
    active: true,
    target: "_blank",
    note: "Added from provided embed snippet.",
  },
    {
    id: "findly.tools",
    name: "findly.tools",
    href: "https://findly.tools/rainbow-magic-fairy-name-finder?utm_source=rainbow-magic-fairy-name-finder",
    mode: "badge",
    badgeSrc: "https://findly.tools/badges/findly-tools-badge-light.svg",
    badgeAlt: "Featured on Findly.tools",
    badgeWidth: 175,
    badgeHeight: 55,
    active: false,
    target: "_blank",
    note: "Stage 1 cleanup: disable linkedin-translator referral badge.",
  },
    {
    id: "LaunchClash",
    name: "LaunchClash",
    href: "https://launchclash.com/product/rainbow-magic-fairy-name-finder",
    mode: "badge",
    badgeSrc: "https://launchclash.com/static/images/badge.png",
    badgeAlt: "Featured on Submit Your Product - LaunchClash",
    badgeHeight: 54,
    active: true,
    target: "_blank",
    note: "Added from provided embed snippet.",
  },
  {
    id: "dokeyai",
    name: "Z-Image",
    href: "https://z-image.net/",
    mode: "link",
    linkLabel: "Z-Image",
    active: true,
    note: "Replace with your actual listing URL and set active to true.",
  },
{
  id: "product-hunt",
  name: "Product Hunt",
  href: "https://www.producthunt.com/products/rainbow-magic-fairy-name-finder?embed=true&utm_source=badge-featured&utm_medium=badge&utm_campaign=badge-rainbow-magic-fairy-name-finder",
  mode: "badge+link",
  badgeSrc: "https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=1129454&theme=light&t=1776825807737",
  badgeAlt: "Rainbow Magic Fairy Name Finder - Find your official Rainbow Magic fairy name instantly | Product Hunt",
  badgeWidth: 250,
  badgeHeight: 54,
  active: true,
},
{
  id: "AI Nav Site",
  name: "AI Sites | 2026",
  href: "https://navs.site",
  mode: "link",
  linkLabel: "AI Nav Site",
  active: true,
  note: "Replace with your actual listing URL and set active to true.",
},
{
  id: "ShowMySites",
  name: "ShowMySites",
  href: "https://www.showmysites.com",
  mode: "badge+link",
  badgeSrc: "https://www.showmysites.com/static/backlink/blue_border.webp",
  badgeAlt: "ShowMySites Badge",
  badgeWidth: 200,
  badgeHeight: 60,
  active: true,
},


];
