import type { DirectoryBadgeItem } from "./directory-badges";

export const DIRECTORY_BADGE_ITEMS: DirectoryBadgeItem[] = [
  {
    // Link-only example
    id: "directory-link-example",
    name: "Directory Example",
    href: "https://example.com/your-listing",
    mode: "link",
    linkLabel: "Listed on Directory Example",
    active: false,
    note: "Replace with your actual listing URL and set active to true.",
  },
  {
    // Badge + link example
    id: "directory-badge-example",
    name: "Badge Example",
    href: "https://example.com/your-listing",
    mode: "badge+link",
    badgeSrc: "https://img.shields.io/badge/Listed-Example-blue",
    badgeAlt: "Listed on Example",
    badgeWidth: 200,
    badgeHeight: 54,
    active: false,
    note: "Use the badge image provided by each directory.",
  },
  {
    id: "Z-Image",
    name: "Z-Image",
    href: "https://z-image.net",
    mode: "link",
    linkLabel: "Z-Image",
    active: true,
    note: "Replace with your actual listing URL and set active to true.",
  },
  {
    id: "wired-business",
    name: "Wired Business",
    href: "https://wired.business",
    mode: "badge",
    badgeSrc: "https://wired.business/badge0-light.svg",
    badgeAlt: "Featured on Wired Business",
    badgeWidth: 200,
    badgeHeight: 54,
    active: true,
    target: "_blank",
    note: "Added from provided embed snippet.",
  },
    {
    id: "showmebest",
    name: "showmebest",
    href: "https://showmebest.ai",
    mode: "badge",
    badgeSrc: "https://showmebest.ai/badge/feature-badge-white.webp",
    badgeAlt: "Featured on ShowMeBestAI",
    badgeWidth: 220,
    badgeHeight: 60,
    active: true,
    target: "_blank",
    note: "Added from provided embed snippet.",
  },
    {
    id: "findly.tools",
    name: "findly.tools",
    href: "https://findly.tools/linkedin-translator?utm_source=linkedin-translator",
    mode: "badge",
    badgeSrc: "https://findly.tools/badges/findly-tools-badge-light.svg",
    badgeAlt: "Featured on Findly.tools",
    badgeWidth: 175,
    badgeHeight: 55,
    active: true,
    target: "_blank",
    note: "Added from provided embed snippet.",
  },
    {
    id: "LaunchClash",
    name: "LaunchClash",
    href: "https://launchclash.com",
    mode: "badge",
    badgeSrc: "https://launchclash.com/static/images/badge.png",
    badgeAlt: "LaunchClash",
    badgeHeight: 54,
    active: true,
    target: "_blank",
    note: "Added from provided embed snippet.",
  },

];
